// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agama.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	agama.proto

It has these top-level messages:
	AddAgamaReq
	ReadAgamaByKeteranganReq
	ReadAgamaByKeteranganResp
	ReadAgamaResp
	UpdateAgamaReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddAgamaReq struct {
	IDAgama    string `protobuf:"bytes,1,opt,name=IDAgama" json:"IDAgama,omitempty"`
	NamaAgama  string `protobuf:"bytes,2,opt,name=NamaAgama" json:"NamaAgama,omitempty"`
	Status     int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	Keterangan string `protobuf:"bytes,4,opt,name=Keterangan" json:"Keterangan,omitempty"`
	CreateBy   string `protobuf:"bytes,5,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *AddAgamaReq) Reset()                    { *m = AddAgamaReq{} }
func (m *AddAgamaReq) String() string            { return proto.CompactTextString(m) }
func (*AddAgamaReq) ProtoMessage()               {}
func (*AddAgamaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddAgamaReq) GetIDAgama() string {
	if m != nil {
		return m.IDAgama
	}
	return ""
}

func (m *AddAgamaReq) GetNamaAgama() string {
	if m != nil {
		return m.NamaAgama
	}
	return ""
}

func (m *AddAgamaReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddAgamaReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *AddAgamaReq) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadAgamaByKeteranganReq struct {
	Keterangan string `protobuf:"bytes,1,opt,name=Keterangan" json:"Keterangan,omitempty"`
}

func (m *ReadAgamaByKeteranganReq) Reset()                    { *m = ReadAgamaByKeteranganReq{} }
func (m *ReadAgamaByKeteranganReq) String() string            { return proto.CompactTextString(m) }
func (*ReadAgamaByKeteranganReq) ProtoMessage()               {}
func (*ReadAgamaByKeteranganReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadAgamaByKeteranganReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type ReadAgamaByKeteranganResp struct {
	IDAgama    string `protobuf:"bytes,1,opt,name=IDAgama" json:"IDAgama,omitempty"`
	NamaAgama  string `protobuf:"bytes,2,opt,name=NamaAgama" json:"NamaAgama,omitempty"`
	Status     int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	Keterangan string `protobuf:"bytes,4,opt,name=Keterangan" json:"Keterangan,omitempty"`
	CreateBy   string `protobuf:"bytes,5,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *ReadAgamaByKeteranganResp) Reset()                    { *m = ReadAgamaByKeteranganResp{} }
func (m *ReadAgamaByKeteranganResp) String() string            { return proto.CompactTextString(m) }
func (*ReadAgamaByKeteranganResp) ProtoMessage()               {}
func (*ReadAgamaByKeteranganResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadAgamaByKeteranganResp) GetIDAgama() string {
	if m != nil {
		return m.IDAgama
	}
	return ""
}

func (m *ReadAgamaByKeteranganResp) GetNamaAgama() string {
	if m != nil {
		return m.NamaAgama
	}
	return ""
}

func (m *ReadAgamaByKeteranganResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadAgamaByKeteranganResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *ReadAgamaByKeteranganResp) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadAgamaResp struct {
	AllAgama []*ReadAgamaByKeteranganResp `protobuf:"bytes,1,rep,name=allAgama" json:"allAgama,omitempty"`
}

func (m *ReadAgamaResp) Reset()                    { *m = ReadAgamaResp{} }
func (m *ReadAgamaResp) String() string            { return proto.CompactTextString(m) }
func (*ReadAgamaResp) ProtoMessage()               {}
func (*ReadAgamaResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadAgamaResp) GetAllAgama() []*ReadAgamaByKeteranganResp {
	if m != nil {
		return m.AllAgama
	}
	return nil
}

type UpdateAgamaReq struct {
	IDAgama    string `protobuf:"bytes,1,opt,name=IDAgama" json:"IDAgama,omitempty"`
	NamaAgama  string `protobuf:"bytes,2,opt,name=NamaAgama" json:"NamaAgama,omitempty"`
	Status     int32  `protobuf:"varint,3,opt,name=Status" json:"Status,omitempty"`
	Keterangan string `protobuf:"bytes,4,opt,name=Keterangan" json:"Keterangan,omitempty"`
	UpdateBy   string `protobuf:"bytes,5,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
}

func (m *UpdateAgamaReq) Reset()                    { *m = UpdateAgamaReq{} }
func (m *UpdateAgamaReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateAgamaReq) ProtoMessage()               {}
func (*UpdateAgamaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateAgamaReq) GetIDAgama() string {
	if m != nil {
		return m.IDAgama
	}
	return ""
}

func (m *UpdateAgamaReq) GetNamaAgama() string {
	if m != nil {
		return m.NamaAgama
	}
	return ""
}

func (m *UpdateAgamaReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateAgamaReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

func (m *UpdateAgamaReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func init() {
	proto.RegisterType((*AddAgamaReq)(nil), "grpc.AddAgamaReq")
	proto.RegisterType((*ReadAgamaByKeteranganReq)(nil), "grpc.ReadAgamaByKeteranganReq")
	proto.RegisterType((*ReadAgamaByKeteranganResp)(nil), "grpc.ReadAgamaByKeteranganResp")
	proto.RegisterType((*ReadAgamaResp)(nil), "grpc.ReadAgamaResp")
	proto.RegisterType((*UpdateAgamaReq)(nil), "grpc.UpdateAgamaReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for AgamaService service

type AgamaServiceClient interface {
	AddAgama(ctx context.Context, in *AddAgamaReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadAgamaByKeterangan(ctx context.Context, in *ReadAgamaByKeteranganReq, opts ...grpc1.CallOption) (*ReadAgamaByKeteranganResp, error)
	ReadAgama(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadAgamaResp, error)
	UpdateAgama(ctx context.Context, in *UpdateAgamaReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type agamaServiceClient struct {
	cc *grpc1.ClientConn
}

func NewAgamaServiceClient(cc *grpc1.ClientConn) AgamaServiceClient {
	return &agamaServiceClient{cc}
}

func (c *agamaServiceClient) AddAgama(ctx context.Context, in *AddAgamaReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgamaService/AddAgama", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agamaServiceClient) ReadAgamaByKeterangan(ctx context.Context, in *ReadAgamaByKeteranganReq, opts ...grpc1.CallOption) (*ReadAgamaByKeteranganResp, error) {
	out := new(ReadAgamaByKeteranganResp)
	err := grpc1.Invoke(ctx, "/grpc.AgamaService/ReadAgamaByKeterangan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agamaServiceClient) ReadAgama(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadAgamaResp, error) {
	out := new(ReadAgamaResp)
	err := grpc1.Invoke(ctx, "/grpc.AgamaService/ReadAgama", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agamaServiceClient) UpdateAgama(ctx context.Context, in *UpdateAgamaReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.AgamaService/UpdateAgama", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgamaService service

type AgamaServiceServer interface {
	AddAgama(context.Context, *AddAgamaReq) (*google_protobuf.Empty, error)
	ReadAgamaByKeterangan(context.Context, *ReadAgamaByKeteranganReq) (*ReadAgamaByKeteranganResp, error)
	ReadAgama(context.Context, *google_protobuf.Empty) (*ReadAgamaResp, error)
	UpdateAgama(context.Context, *UpdateAgamaReq) (*google_protobuf.Empty, error)
}

func RegisterAgamaServiceServer(s *grpc1.Server, srv AgamaServiceServer) {
	s.RegisterService(&_AgamaService_serviceDesc, srv)
}

func _AgamaService_AddAgama_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAgamaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgamaServiceServer).AddAgama(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgamaService/AddAgama",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgamaServiceServer).AddAgama(ctx, req.(*AddAgamaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgamaService_ReadAgamaByKeterangan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAgamaByKeteranganReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgamaServiceServer).ReadAgamaByKeterangan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgamaService/ReadAgamaByKeterangan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgamaServiceServer).ReadAgamaByKeterangan(ctx, req.(*ReadAgamaByKeteranganReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgamaService_ReadAgama_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgamaServiceServer).ReadAgama(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgamaService/ReadAgama",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgamaServiceServer).ReadAgama(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgamaService_UpdateAgama_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgamaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgamaServiceServer).UpdateAgama(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.AgamaService/UpdateAgama",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgamaServiceServer).UpdateAgama(ctx, req.(*UpdateAgamaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgamaService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.AgamaService",
	HandlerType: (*AgamaServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddAgama",
			Handler:    _AgamaService_AddAgama_Handler,
		},
		{
			MethodName: "ReadAgamaByKeterangan",
			Handler:    _AgamaService_ReadAgamaByKeterangan_Handler,
		},
		{
			MethodName: "ReadAgama",
			Handler:    _AgamaService_ReadAgama_Handler,
		},
		{
			MethodName: "UpdateAgama",
			Handler:    _AgamaService_UpdateAgama_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "agama.proto",
}

func init() { proto.RegisterFile("agama.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x65, 0xf9, 0x12, 0xa6, 0x6a, 0xe2, 0xa8, 0xa4, 0x56, 0x83, 0x64, 0x4f, 0x9c, 0x96, 0x04,
	0x0f, 0x26, 0x18, 0x0f, 0xa0, 0x1e, 0x8c, 0xc6, 0x43, 0x89, 0x17, 0x6f, 0x03, 0xac, 0x8d, 0x09,
	0xd0, 0x52, 0x16, 0x13, 0x7e, 0x8a, 0x89, 0xf1, 0xea, 0xdf, 0x34, 0xdd, 0xa5, 0xe5, 0x23, 0x56,
	0x8f, 0x7a, 0x7c, 0x33, 0xf3, 0x26, 0xef, 0xcd, 0x3c, 0xb0, 0xc8, 0xa3, 0x11, 0x89, 0x20, 0xf4,
	0x95, 0x8f, 0x79, 0x2f, 0x0c, 0xfa, 0xce, 0xb1, 0xe7, 0xfb, 0xde, 0x50, 0x36, 0x74, 0xad, 0x37,
	0x7b, 0x6e, 0xc8, 0x51, 0xa0, 0xe6, 0x66, 0x84, 0xbf, 0x31, 0xb0, 0xda, 0x83, 0x41, 0x3b, 0x62,
	0xb9, 0x72, 0x82, 0x36, 0x6c, 0xdd, 0x5e, 0x6b, 0x64, 0xb3, 0x1a, 0xab, 0x97, 0xdd, 0x18, 0xe2,
	0x09, 0x94, 0x1f, 0x68, 0x44, 0xa6, 0x97, 0xd5, 0xbd, 0x65, 0x01, 0x2b, 0x50, 0xec, 0x2a, 0x52,
	0xb3, 0xa9, 0x9d, 0xab, 0xb1, 0x7a, 0xc1, 0x5d, 0x20, 0xac, 0x02, 0xdc, 0x49, 0x25, 0x43, 0x1a,
	0x7b, 0x34, 0xb6, 0xf3, 0x9a, 0xb6, 0x52, 0x41, 0x07, 0x4a, 0x57, 0xa1, 0x24, 0x25, 0x3b, 0x73,
	0xbb, 0xa0, 0xbb, 0x09, 0xe6, 0x2d, 0xb0, 0x5d, 0x49, 0x46, 0x5b, 0x67, 0xbe, 0x24, 0x45, 0x3a,
	0xd7, 0xf7, 0xb2, 0xcd, 0xbd, 0xfc, 0x93, 0xc1, 0x51, 0x0a, 0x79, 0x1a, 0xfc, 0x2b, 0x97, 0xf7,
	0xb0, 0x93, 0x08, 0xd5, 0xe2, 0x2e, 0xa0, 0x44, 0xc3, 0x61, 0xac, 0x2e, 0x57, 0xb7, 0x9a, 0xa7,
	0x22, 0x7a, 0xa4, 0x48, 0xf5, 0xe3, 0x26, 0x04, 0xfe, 0xce, 0x60, 0xf7, 0x31, 0x18, 0x90, 0x92,
	0x7f, 0xf9, 0x52, 0xa3, 0x60, 0x69, 0x36, 0xc6, 0xcd, 0x8f, 0x2c, 0x6c, 0xeb, 0xed, 0x5d, 0x19,
	0xbe, 0xbe, 0xf4, 0x25, 0x9e, 0x43, 0x29, 0x8e, 0x1f, 0xee, 0x19, 0x9b, 0x2b, 0x71, 0x74, 0x2a,
	0xc2, 0x84, 0x57, 0xc4, 0xe1, 0x15, 0x37, 0x51, 0x78, 0x79, 0x06, 0x9f, 0xe0, 0xf0, 0xdb, 0x7b,
	0x60, 0xf5, 0xc7, 0x63, 0x4d, 0x9c, 0xdf, 0x8e, 0xc9, 0x33, 0xd8, 0x82, 0x72, 0xd2, 0xc6, 0x14,
	0x09, 0xce, 0xfe, 0xc6, 0x9e, 0x05, 0xf7, 0x12, 0xac, 0x95, 0xfb, 0xe3, 0x81, 0x99, 0x5a, 0x7f,
	0x49, 0xba, 0xad, 0x5e, 0x51, 0x57, 0xce, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x76, 0xb1, 0x44,
	0x49, 0xc8, 0x03, 0x00, 0x00,
}
